version: '3.8'
services:
  # frontend:
  #   container_name: frontend
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports: 
  #     - 3000:3000
  #   depends_on:
  #     - backend
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 3567:5000