version: '3.8'
services:
  frontend:
    container_name: frontend
    build: 
      context: ./frontend/my_notes
      dockerfile: Dockerfile
    ports: 
      - 80:80
    depends_on:
      - backend
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - 3567:3567